# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation', models.CharField(max_length=1000)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neuralnet.Layer')),
            ],
        ),
        migrations.AddField(
            model_name='layer',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neuralnet.Network'),
        ),
    ]
